version: '3.12'

services:

  backend:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    network_mode: host
  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_DB: system_memory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
